// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtsS6CwKU5ThvsFdV1rRfaPbmn4-LqY-c',
    appId: '1:776232128891:web:c79e6e5b7548b1d2152dde',
    messagingSenderId: '776232128891',
    projectId: 'chatbox-ee37f',
    authDomain: 'chatbox-ee37f.firebaseapp.com',
    storageBucket: 'chatbox-ee37f.firebasestorage.app',
    measurementId: 'G-PP5MZ8NEMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuP_ZnoBxipXOFiTReGL2-9EcjsSyISNI',
    appId: '1:776232128891:android:c4f949b05bbec030152dde',
    messagingSenderId: '776232128891',
    projectId: 'chatbox-ee37f',
    storageBucket: 'chatbox-ee37f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-pv9s9ct1_bENzYYJXeCiBwFCJ7bUWE',
    appId: '1:776232128891:ios:9f62b061b8365013152dde',
    messagingSenderId: '776232128891',
    projectId: 'chatbox-ee37f',
    storageBucket: 'chatbox-ee37f.firebasestorage.app',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH-pv9s9ct1_bENzYYJXeCiBwFCJ7bUWE',
    appId: '1:776232128891:ios:9f62b061b8365013152dde',
    messagingSenderId: '776232128891',
    projectId: 'chatbox-ee37f',
    storageBucket: 'chatbox-ee37f.firebasestorage.app',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtsS6CwKU5ThvsFdV1rRfaPbmn4-LqY-c',
    appId: '1:776232128891:web:3724cf015d0b9edc152dde',
    messagingSenderId: '776232128891',
    projectId: 'chatbox-ee37f',
    authDomain: 'chatbox-ee37f.firebaseapp.com',
    storageBucket: 'chatbox-ee37f.firebasestorage.app',
    measurementId: 'G-PQEDX4PQLK',
  );
}
